### ISSUE TITLE
Add .bib for each of the following: Cāng Jiépiān 蒼頡篇, Wàngjī 妄 稽, Shénwūfù 神烏賦, Kǒngzǐ yī jìng 孔子衣鏡, and Fǎnyín 反淫

### ISSUE THREAD

**Issue by nh36** [hanproj/bamboo-and-wood#1]
- [x] Cāng Jiépiān 蒼頡篇
- [x] Wàngjī 妄 稽 
- [x] Shénwūfù 神烏賦 
- [x] Kǒngzǐ yī jìng 孔子衣鏡 
- [x] Fǎnyín 反淫

**Comment by nh36** [comment]
@LinguList Sorry for such a stupid question, but the only bibliographic thing left is Chris blogpost, and I am not sure what type of bibtex record to put it in. Maybe you already have it in your bibliography?

**Comment by LinguList** [comment]
```
Christopher J. Foster, “Annotating Rhyme Judgments for a Complex Corpus of Manuscript Sources: Making Sense of the «Cang Jie pian 蒼頡篇»,” in Computer-Assisted Language Comparison in Practice, 14/10/2020, https://calc.hypotheses.org/2525.
```

In Bibtex, we treat it as a journal:

```
@article{Foster2020,
  year = {2022}, 
  author = {Christopher J. Foster},
  title = {Annotating Rhyme Judgments for a Complex Corpus of Manuscript Sources: Making Sense of the «Cang Jie pian 蒼頡篇»},
  journal = {Computer-Assisted Language Comparison in Practice},
  volume = {3},
  number = {1},
  url = {https://calc.hypotheses.org/2525}
}
```

We also have page numbers, but I'd have to dig them out (we publish a PDF of all articles now, by then, we did one big pdf with all articles once a year). It is like a journal without peer review.

**Comment by nh36** [comment]
Can you just give a link here of where you publish the .pdfs? I can find it.

**Comment by LinguList** [comment]
https://hcommons.org/?s=computer-assisted+language+comparison+in+practice

They are all on humanities commons.

**Comment by nh36** [comment]
Thanks, pp. 72-86.
